name: Prettier and ESLint Check

# This action works with pull requests to main and optional pushes
on:
  pull_request:
    branches:
      - main # Detta körs när någon öppnar eller uppdaterar en PR till main
  push:
    branches:
      - main # Detta körs varje gång kod pushas till main
      - test-2-actions # Din testbranch

jobs:
  lint_and_prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run ESLint with fix
        run: npm run lint -- --fix

      - name: Run Prettier
        run: npm run format
